sudo: false
dist: trusty
sudo: required
language: python
python:
  - "2.7"
before_install:
  - wget 'http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh' -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - sudo apt-get update
  - sudo apt-get install libc6
install:
  - conda create --yes -n shorttext-test python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - source activate shorttext-test
  - pip install unittest2
  - pip install pytest
  - sudo pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
  - pip install -U .
script: python shorttext_tests.py