language: python
python:
  - "2.7"
before_install:
  - wget 'http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh' -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  - cd /tmp
  - wget http://launchpadlibrarian.net/137699828/libc6_2.17-0ubuntu5_amd64.deb
  - wget http://launchpadlibrarian.net/137699829/libc6-dev_2.17-0ubuntu5_amd64.deb
  - mkdir libc6_2.17
  - cd libc6_2.17
  - ar p ../libc6_2.17-0ubuntu5_amd64.deb data.tar.gz | tar zx
  - ar p ../libc6-dev_2.17-0ubuntu5_amd64.deb data.tar.gz | tar zx
  - cd -
  - LD_LIBRARY_PATH=/tmp/libc6_2.17/lib/x86_64-linux-gnu/ /tmp/libc6_2.17/lib/x86_64-linux-gnu/ld-2.17.so bin/python local/lib/python2.7/site-packages/tensorflow/models/image/mnist/convolutional.py
install:
  - conda create --yes -n shorttext-test python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - source activate shorttext-test
  - pip install unittest2
  - pip install pytest
  - pip install tensorflow
  - pip install -U .
script: python shorttext_tests.py